[workspace]
resolver = "3"
members = ["demo","dioxus-leaflet"]

[workspace.dependencies]
dioxus = "0.7.0-rc.0"
dioxus-leaflet = { path = "dioxus-leaflet" }

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
